name: admin_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  fl_chart: ^1.2.0
  google_fonts: ^8.1.0
  flutter_riverpod: ^3.3.1
  lucide_icons: ^0.257.0
  animations: ^2.2.0
  image_picker: ^1.2.2
  permission_handler: ^11.3.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  provider: ^6.1.2
  flutter_typeahead: ^5.2.0
  file_picker: 8.1.2
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  pdf: ^3.12.0
  printing: ^5.14.3
  path_provider: ^2.1.5
  share_plus: ^12.0.2
  http: ^1.6.0
  shared_preferences: ^2.5.5
  google_maps_flutter: ^2.17.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  dropdown_search: ^7.0.0
  url_launcher: ^6.3.1
  razorpay_flutter: ^1.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
